# Manual Beanstalk Deployment Pipeline using Reusable Builder
name: Beanstalk Deployment (Manual)
on:
  workflow_dispatch:

jobs:
  # 1. Call the shared build and push workflow
  build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit

  # 2. Deploy to Beanstalk after build finishes
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container-compute-hub
          environment_name: Multi-container-compute-hub-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: docker-compose.yml
