# Primary GKE Deployment Pipeline using Reusable Builder
name: GKE Deployment
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'ARCHITECTURE.md'
      - 'README.md'
  workflow_dispatch:

jobs:
  # 1. Call the shared build and push workflow
  build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit

  # 2. Deploy to GKE after build finishes
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Service Account Key
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: Get GKE Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: computehub-multi-k8s
          location: us-central1-a
      
      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=vikas9dev/computehub-client:${{ github.sha }}
          kubectl set image deployments/server-deployment server=vikas9dev/computehub-server:${{ github.sha }}
